name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest

   steps:
   - name: Check out code
     uses: actions/checkout@v2

   - name: Set up Python
     uses: actions/setup-python@v2
     with:
       python-version: '3.10'
  
   - name: Install Dependencies
     run: |
       python -m pip install --upgrade pip
       pip install -r requirements.txt

   - name: Lint with Flake8
     run: |
       flake8 .
   
   - name: Run Tests unitest
     run: | 
       python -m unittest -v

   - name: Run Doctest
     run: | 
       python -m doctest -v library/*.py
   
   - name: Build & push Docker image
     uses: mr-smithers-excellent/docker-build-push@v5
     with:
      image: sahamada/demo-poo-python
      tags: latest
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_PASSWORD }}